config/routes.rb
Rails.application.routes.draw do
  root to: "home_page#discovers"

  get '/feeds', to: "home_page#feeds"
  get '/managers/photo', to: "admin#photo"
  get '/managers/album', to: "admin#album"
  get '/managers/user', to: "admin#user"

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users do
    member do
      get :followings, :followers
    end
  end

  resources :albums do
    resources :likes, only: [:create, :destroy], module: :albums
    resources :images, :only => [:create, :destroy]
  end

  resources :photos do
    resources :likes, only: [:create, :destroy], module: :photos
  end

  resources :relationships,       only: [:create, :destroy]
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  PAGE = 4
  before_action :authenticate_user!
  def feeds
    @users = current_user.followings.ids
    @photos_feeds = Photo.where(user_id: @users).published_photo.paginate(page: params[:page_photos], per_page: PAGE)
    @albums_feeds = Album.where(user_id: @users).published_album.paginate(page: params[:page_albums], per_page: PAGE)
  end

  def discovers
    puts '---------------------------------------------'
    puts params[:page_photos]
    @photos_discovers = Photo.published_photo.where.not(user_id: current_user).paginate(page: params[:page_photos], per_page: PAGE)
    @albums_discovers = Album.published_album.where.not(user_id: current_user).paginate(page: params[:page_albums], per_page: PAGE)
  end
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/views/home_page/_album_tab.html.erb
<div class="row" id="albums_tab">
  <% albums.each do |album| %>
    <% if !album.sharing_mode == false %>
      <div class="col-sm-12 col-md-6 p-0 mt-2 d-flex" >
        <div class="container-fluid m-2 border rounded">
          <div class="row">
            <%= link_to album_path(album), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#modal_album'} do %>
            <div class="col-12 col-sm-12 col-lg-6 mt-3 w-100" data-toggle="modal" data-target="#modalAlbum">
              <div class="size-photos d-flex justify-content-center m-0">
                <% album.images.each_with_index do |photo, index| %>
                  <% if (index != album.images.length - 1) && (index < 4)  %>
                    <% a = (index*3+3).to_s %>
                    <%= image_tag photo.url, {class:"rounded-sm size-photos", style:"position: absolute; z-index: index; transform: rotate("+ a +"deg)"} %>
                  <% else %>
                    <%= image_tag photo.url, {class:"rounded-sm size-photos", style:"position: absolute; z-index: index;"} %>
                  <% end %>
                <% end %>
              </div>
            </div>
            <% end %>
            <div class="col-lg-6 pr-0 mt-2">
              <div>
                <%unless current_user.id == album.user.id %>
                  <div id="follow_form_feeds_album_<%= album.user.id %>">
                    <% if home %>
                    <%= render 'follow_home', user: album.user %>
                    <% end %>
                  </div>
                <% end %>
                <a href="<%= user_path(album.user) %>" class="nav-link d-inline-flex p-0">
                  <img src="<%= album.user.avatar %>" class="rounded-circle" id="avatar_top">
                  <p class="text-primary pt-2 pl-2"><b><%= album.user.full_name %></b></p>
                </a>
              </div>
              <div class="pr-2 style-post" data-toggle="modal" data-target="#modalAlbum">
                <h4><b><%= album.title %></b></h4>
                <p><%= album.description %></p>
              </div>
              <div class="container d-inline pl-0 b-line">
                <div class="d-inline-flex">
                  <%= render 'like_form_album', post: album %>
                  <p id="count_album_<%= album.id %>"class="like-number"><b> <%= album.likes.size %></b></p>
                </div>
                <small class="pt-3 float-right "><%= album.created_at.strftime("%I:%M %p %-d/%-m/%Y") %></small>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<div class="d-flex justify-content-center mt-3">
  <%= will_paginate albums, param_name: 'page_albums', renderer: WillPaginate::ActionView::BootstrapLinkRenderer, previous_label:"<<", next_label: ">>", inner_window: 0, outer_window: 0, params: {active: 'page_albums'}%>
</div>

app/views/home_page/_follow_home.html.erb
<% if current_user.following?(user) %>
  <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
               html: { method: :delete },
               remote: true) do |f| %>
    <%= f.submit "Unfollow", class: "btn following-home" %>
  <% end %>
<% else %>
  <%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
    <div><%= hidden_field_tag :followed_id, user.id %></div>
    <%= f.submit "Follow", class: "btn follow-home"%>
  <% end %>
<% end %>

app/views/home_page/_like_form_album.html.erb
<div id="album_<%= post.id %>">
  <% pre_like = post.likes.find { |like| like.user == current_user} %>
  <% if pre_like %>
    <%= link_to album_like_path(post,pre_like), method: :delete, remote: true  do %>
      <img class="btn-like" src="/assets/like.png">
    <% end %>
  <% else %>
    <%= link_to album_likes_path(post), method: :post, remote: true do %>
      <img class="btn-like" src="/assets/heart.png">
    <% end %>
  <% end %>
</div>

app/views/home_page/_like_form_photo.html.erb
<div id="photo_<%= post.id %>">
  <% pre_like = post.likes.find { |like| like.user == current_user} %>
  <% if pre_like %>
    <%= link_to photo_like_path(post,pre_like), method: :delete, remote: true  do %>
      <img class="btn-like" src="/assets/like.png">
    <% end %>
  <% else %>
    <%= link_to photo_likes_path(post), method: :post, remote: true do %>
      <img class="btn-like" src="/assets/heart.png">
    <% end %>
  <% end %>
</div>

app/views/home_page/_photo_tab.html.erb
<div class="row d-flex" id="photos_tab">
  <% photos.each do |photo| %>
    <% if !photo.sharing_mode == false %>
      <div class="col-sm-12 col-md-12 col-lg-6  d-flex mt-2" id="post_photo_<%= photo.user.id %>" >
        <div class="container-fluid m-1 border rounded">
          <div class="row">
            <%= link_to photo_path(photo), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal_photo', class: 'col-12 col-sm-12 col-md-6 p-1'} do %>
              <div class=" size-albums">
                <img class="rounded-lg w-100 h-100 pr-2" src="<%= url_for(photo.image) %>">
              </div>
            <% end %>
            <div class="col-md-6">
              <div class="mt-1">
                <%unless current_user.id == photo.user.id %>
                  <div id="follow_form_feeds_photo_<%= photo.user.id %>">
                    <% if home %>
                      <%= render 'follow_home', user: photo.user %>
                    <% end %>
                  </div>
                <% end %>
                <a href="<%= user_path(photo.user) %>" class="nav-link d-inline-flex p-0">
                  <img src="<%= photo.user.avatar %>" class="rounded-circle" id="avatar_top">
                  <p class="text-primary pt-2 pl-2"><b><%= photo.user.full_name %></b></p>
                </a>
              </div>
              <div class="style-post">
                <h4><b><%= photo.title %></b></h4>
                <p><%= photo.description %></p>
              </div>
              <div class="container d-inline pl-0 b-line">
                <div class="d-inline-flex">
                  <%= render 'like_form_photo', post: photo %>
                  <p id="count_photo_<%= photo.id %>" class="like-number"><b> <%= photo.likes.size %></b></p>
                </div>
                <small class="pt-3 pr-2 float-right "><%= photo.created_at.strftime("%I:%M %p %-d/%-m/%Y") %></small>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<div class="d-flex justify-content-center mt-3">
  <%= will_paginate photos, param_name: 'page_photos', renderer: WillPaginate::ActionView::BootstrapLinkRenderer, previous_label:"<<", next_label: ">>", inner_window: 0, outer_window: 0, params: {active: 'page_photos'}, remote: true %>
</div>

app/views/home_page/discovers.html.erb
<% provide(:title, "Discovers") %>
<%= render 'layouts/toolbar' %>
<%= render 'layouts/view_modal' %>
<section class="container-fluid p-0">
  <!--Tab feeds va discover-->
  <div class="row">
    <%= render '/layouts/tab_feeds'%>

    <article class="tab-content col-md-8 p-0 bg-white" >
      <!-- feeds Page-->
      <div id="feedsPage" class="container-fluid tab-pane active p-0">
        <div class="d-flex justify-content-center mb-2">
          <ul class="nav nav-tabs btn-group btn-group-md pt-3">
            <li class="nav-item btn btn-white">
                <a class="navbar-brand active" data-toggle="tab" href="#photoDiscovers"><b>PHOTO</b></a>
            </li>
            <li class="nav-item btn btn-primary">
                <a class="navbar-brand text-white" data-toggle="tab" href="#albumDiscovers"><b>ALBUM</b></a>
            </li>
          </ul>
        </div>
        <!-- end button PHOTO and ALBUM-->

        <div class="container-fluid tab-pane active">
          <!-- Tab panes -->
          <div class="tab-content">
            <!-- tab hinh anh -->
            <div class="container-fluid tab-pane active" id="photoDiscovers">
              <%= render 'photo_tab', photos: @photos_discovers, home: true %>
            </div>
            <!--  tab album -->
            <div class="container-fluid tab-pane fade" id="albumDiscovers">
              <%= render 'album_tab', albums: @albums_discovers, home: true %>
            </div> <!-- end tab contents -->
          </div>
        </div>
      </div> <!--end teb feedsPage-->
    </article>
  </div>
</section>

app/views/home_page/feeds.html.erb
<% provide(:title, "Feeds") %>
<%= render 'layouts/toolbar' %>
<%= render 'layouts/view_modal' %>
<section class="container-fluid p-0">
    <!--Tab feeds va discover-->
    <div class="row">
      <%= render '/layouts/tab_feeds'%>

      <article class="tab-content col-md-8 p-0 bg-white" >
        <!-- feeds Page-->
        <div id="feedsPage" class="container-fluid tab-pane active p-0">
          <div class="d-flex justify-content-center mb-2">
                <ul class="nav nav-tabs btn-group btn-group-md pt-3">
                  <li class="nav-item btn btn-white">
                      <a class="navbar-brand active" data-toggle="tab" href="#photoFeeds"><b>PHOTO</b></a>
                  </li>
                  <li class="nav-item btn btn-primary">
                      <a class="navbar-brand text-white" data-toggle="tab" href="#albumFeeds"><b>ALBUM</b></a>
                  </li>
                </ul>
          </div>
          <!-- end button PHOTO and ALBUM-->

          <div class="container-fluid tab-pane active">
            <!-- Tab panes -->
            <div class="tab-content">
              <!-- tab hinh anh -->
              <div class="container-fluid tab-pane active" id="photoFeeds">
                <%= render 'photo_tab', photos: @photos_feeds, home: false %>
              </div>
              <!--  tab album -->
              <div class="container-fluid tab-pane fade" id="albumFeeds">
                      <%= render 'album_tab', albums: @albums_feeds, home: false %>
              </div> <!-- end tab contents -->
            </div>
          </div>
        </div> <!--end teb feedsPage-->
      </article>
    </div>
  </section>