config/routes.rb
Rails.application.routes.draw do
  root to: "home_page#discovers"

  get '/feeds', to: "home_page#feeds"
  get '/managers/photo', to: "admin#photo"
  get '/managers/album', to: "admin#album"
  get '/managers/user', to: "admin#user"

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users do
    member do
      get :followings, :followers
    end
  end

  resources :albums do
    resources :likes, only: [:create, :destroy], module: :albums
    resources :images, :only => [:create, :destroy]
  end

  resources :photos do
    resources :likes, only: [:create, :destroy], module: :photos
  end

  resources :relationships,       only: [:create, :destroy]
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy
  # has_many :image_albums
  # accepts_nested_attributes_for :image_albums, allow_destroy: true
  mount_uploaders :images, ImagesUploader

  scope :published_album, -> {
    where(sharing_mode: true)
  }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy
  has_one_attached :image
  scope :published_photo, -> {
    where(sharing_mode: true)
  }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  has_many :albums, dependent: :destroy
  has_many :likes, dependent: :destroy

  #for button follow in profile page
  has_many :active_relationships, class_name:  "Relationship",
                                foreign_key: "follower_id",
                                dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                 foreign_key: "followed_id",
                                 dependent:   :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :photos, through: :likes, source: :likeable, source_type: 'Photo'
  has_many :albums, through: :likes, source: :likeable, source_type: 'Album'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/assets/logoLogin.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def full_name
    [first_name, last_name].select(&:present?).join(' ').titleize
  end

  # Follows a user.
  def follow(other_user)
    followings << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    followings.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    followings.include?(other_user)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_admin_user!

  def photo
    @photos = Photo.all.paginate(page: params[:page], per_page: 10)
  end

  def album
    @albums = Album.all.paginate(page: params[:page], per_page: 10)
  end

  def user
    @users = User.all.paginate(page: params[:page], per_page: 10)
  end

  def ensure_admin_user!
    unless current_user and current_user.admin?
      redirect_to root_path
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_album, except: [:index, :new, :create, :delete_image_attachment]
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @album = Album.new
    @album.user = current_user
  end

  def edit
  end

  def create
    @album = Album.new(album_params)
    @album.images = params[:images]
    @album.user = current_user

    respond_to do |format|
      if @album.save
        format.html { redirect_to current_user, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: current_user }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to current_user, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: current_user }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_album
      @album = Album.find(params[:id])
    end

    def album_params
      params.require(:album).permit(:title, :description, :sharing_mode, {images: []})
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_album

  def create
    if images_params[:images]
      add_more_images(images_params[:images])
    end
    @album.save
    redirect_to current_user
  end

  def destroy
    remove_image_at_index(params[:id].to_i)
    @album.save
    redirect_back(fallback_location: root_path)
  end

  private

  def set_album
    @album = Album.find(params[:album_id])
  end

  def add_more_images(new_images)
    images = @album.images
    images += new_images
    @album.images = images
  end

  def remove_image_at_index(index)
     remain_images = @album.images
     if index == 0 && @album.images.size == 1
       @album.remove_images!
     else
       deleted_image = remain_images.delete_at(index)
       deleted_image.try(:remove!)
       @album.images = remain_images
     end
  end

  def images_params
    params.require(:album).permit({images: []})
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:edit, :update, :show, :destroy ]
  def index
    @users = User.all
  end

  def edit
  end


   def update
     if @user.update(user_params)
       redirect_to :admin
     else
       render 'edit'
     end
   end

  def show
    @get_photos = Photo.where(user_id: @user.id)
    @get_albums = Album.where(user_id: @user.id)
    @get_followings = @user.followings
    @get_followers = @user.followers
  end

  def destroy
    if @user.present?
      @user.destroy
    end
    redirect_to :admin
  end

  def followings
    @title = "Followings"
    @user  = User.find(params[:id])
    @users = @user.followings.paginate(page: params[:page])
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :activated)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def custom_bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_album_show.html.erb
<div class="col-12 col-sm-6 col-md-4 col-lg-3 text-center">
  <div class="admin-photos d-flex justify-content-center m-4 text-center">
    <% album.images.each_with_index do |photo, index| %>
      <% if (index != album.images.length - 1) %>
        <% a = ((album.images.length.to_i - index)*3).to_s %>
        <%= image_tag photo.url, {class:"rounded-sm admin-photos", style:"position: absolute; z-index: index; transform: rotate("+ a +"deg)"} %>
      <% else %>
        <%= image_tag photo.url, {class:"rounded-sm admin-photos", style:"position: absolute; z-index: index;"} %>
      <% end %>
    <% end %>
    <p class="rounded bg-secondary p-1 title-show-album" style=" position: absolute; z-index: album.images.length + 1;"><%= album.title %></b></p>
    <%= link_to edit_album_path(album)  do%>
      <i class="fas fa-edit bg-secondary icon-edit-album" style="position: absolute; z-index: album.images.length + 2;"></i>
    <% end %>
  </div>
</div>

app/views/admin/_photo_show.html.erb
<div class="col-12 col-sm-6 col-md-4 col-lg-3 text-center">
  <div class="admin-photos d-flex justify-content-center m-2 text-center">
    <img class="rounded-sm admin-photos photo-show" src="<%= url_for(photo.image) %>">
    <p class="rounded bg-secondary p-1 title-show"><%= photo.title %></b></p>
    <%= link_to edit_photo_path(photo) do%>
      <i class="fas fa-edit bg-secondary icon-edit"></i>
    <% end %>
  </div>
</div>

app/views/admin/_tab_manager.html.erb
<div class="col-md-2">
  <div class="container mt-3">
    <div class="navbar navbar-expand-md navbar-light bg-lignt p-0">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class=" collapse navbar-collapse p-0" id="collapsibleNavbar">
        <ul class="navbar-nav nav nav-tabs flex-column">
          <li class="nav-item p-0">
            <a class="nav-link text-primary" href="<%= managers_photo_path %>"><b>Manage Photos</b></a>
          </li>
          <li class="nav-item p-0">
            <a class="nav-link text-primary" href="<%= managers_album_path %>"><b>Manage Albums</b></a>
          </li>
          <li class="nav-item p-0">
            <a class="nav-link text-primary" href="<%= managers_user_path %>"><b>Manage Users</b></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/admin/album.html.erb
<% provide(:title, "Manager Albums") %>
<%= render 'layouts/toolbar' %>
<section class="container-fluid">
    <div class="row ">
      <%= render 'tab_manager' %>

      <article class="col-md-8 p-0 bg-white pt-5" >
        <!--tab manageAlbums-->
        <div class="container tab-pane mt-3">
          <div class="row">
            <% @albums.each do |album| %>
              <%= render 'album_show', album: album %>
            <% end %>
          </div>
          <div class="d-flex justify-content-center mt-3">
            <%= will_paginate @albums, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, previous_label:"<<", next_label: ">>", inner_window: 0, outer_window: 0, remote: true %>
          </div>
        </div>
      </article>
    </div>
  </section>

app/views/admin/photo.html.erb
<% provide(:title, "Manager Photos") %>
<%= render 'layouts/toolbar' %>
<section class="container-fluid">
    <div class="row ">
      <%= render 'tab_manager' %>

      <article class="col-md-8 p-0 bg-white pt-5" >
        <!--tab managePhotos-->
        <div class="container tab-pane ">
          <div class="row">
            <% @photos.each do |photo|  %>
              <%= render 'photo_show', photo: photo %>
            <% end %>
          </div>
          <div class="d-flex justify-content-center mt-3">
            <%= will_paginate @photos, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, previous_label:"<<", next_label: ">>", inner_window: 0, outer_window: 0, remote: true %>
          </div>
        </div>
      </article>
    </div>
  </section>

app/views/admin/user.html.erb
<% provide(:title, "Manager Users") %>
<%= render 'layouts/toolbar' %>
<section class="container-fluid">
    <div class="row ">
      <%= render 'tab_manager' %>

      <article class="col-md-8 p-0 bg-white pt-5" >
        <!--tab ManageUsers-->
        <div class="container tab-pane">
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">First name</th>
                <th scope="col">Last name</th>
                <th scope="col">Email</th>
                <th scope="col">Last Login</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <% if !user.admin %>
                  <tr>
                    <th scope="row"><%= user.first_name %></th>
                    <td><%= user.last_name %></td>
                    <td><%= user.email %></td>
                    <td><%= user.last_sign_in_at %></td>
                    <td>
                      <%= link_to "Edit", edit_user_path(user), class: "btn btn-success mr-2"%>
                      <%= link_to "Delete", user, method: :delete, class: "btn btn-danger"%>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
          <div class="d-flex justify-content-center mt-3">
            <%= will_paginate @users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, previous_label:"<<", next_label: ">>", inner_window: 0, outer_window: 0, remote: true %>
          </div>
        </div>
        <!--end tab ManageUsers-->
      </article>
    </div>
  </section>

app/views/layouts/_tab_feeds.html.erb
<div class="col-md-2">
  <div class="container-fluid mt-3">
    <div class="navbar navbar-expand-md navbar-light bg-lignt pl-5">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class=" collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav nav nav-tabs flex-column">
          <li class="nav-item">
            <b><%= link_to "Feeds", feeds_path, { class: "nav-link text-primary" } %></b>
          </li>
          <li class="nav-item">
            <b><%= link_to "Discovers", root_path, { class: "nav-link text-primary" } %></b>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_toolbar.html.erb
<header class="row">
  <div class="col-0 col-sm-2 col-md-2">
    <a href="<%= root_path %>" class="navbar-brand text-white mt-2 float-right"><h4><b>
      <% if !current_user.nil? && current_user.admin %>
        Focobook Admin
      <% else %>
        Focobook
      <% end %>
  </b></h4></a>
  </div>
  <div class="col-12 col-sm-3 col-md-6">
    <input class="form-control mt-2 w-75" type="search" placeholder="Search Photo/Album" aria-label="Search">
  </div>
  <% if !current_user.nil? %>
    <div class="col-sm-4 col-md-2">
      <a href="<%= user_path(current_user.id) %>" class="nav-link d-inline-flex text-white m-0 float-right">
        <img src="<%=current_user.avatar.url() %>" class="rounded-circle mr-2" id="avatar_top">
        <p class="text-white pt-2 m-0"><b><%= current_user.full_name %></b></p>
      </a>
    </div>
    <% if current_user.admin %>
      <div class="col-sm-1 col-md-1">
        <a href="/managers/photo" class="nav-link text-white pt-3 m-0 float-right"><b>Manager</b></a>
      </div>
    <% end %>
    <div class="col-sm-1 col-md-1">
      <a href="/users/sign_out" data-method="delete" class="nav-link text-white pt-3 m-0 float-right"><b>Logout</b></a>
    </div>
  <% else %>
    <div class="col-sm-3 col-md-1">
    </div>
    <div class="col-sm-1 col-md-1">
      <a href="/users/sign_up" class="nav-link text-white pt-3 m-0 float-right"><b>Sign up</b></a>
    </div>
    <div class="col-sm-1 col-md-1">
      <a href="/users/sign_in" class="nav-link text-white pt-3 m-0 float-left"><b>Log in</b></a>
    </div>
  <% end %>
</header>

<% if notice %>
  <div class="toast rounded float-right note " data-autohide="false" id="notice" >
    <div class="toast-header">
      <strong class="mr-auto">Notification</strong>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </div>
    <div class="toast-body">
      <%= notice %>
    </div>
  </div>
<% end %>

app/views/layouts/_view_modal.html.erb
<!--modal photo-->
<div class="modal fade" id="modal_photo">
  <div class="modal-dialog modal-xl">
    <div class="modal-content"></div>
  </div>
</div><!--end modal Photo-->

<!--modal Album-->
<div class="modal fade" id="modal_album">
  <div class="modal-dialog modal-xl">
    <div class="modal-content"></div>
  </div>
</div>
<!--end modal Album-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.0.4/css/all.css" rel="stylesheet">
    <script src="/assets/activestorage.self-1ed4604ac2170045f1ffca4edb81a75246661555e4f9cf682bb8a21825e32e1c.js?body=1" data-turbolinks-track="reload"></script>

    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= custom_bootstrap_flash %>
  </head>

  <body class="m-0">
    <%= yield %>
  </body>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>