config/routes.rb
Rails.application.routes.draw do
  root to: "home_page#discovers"

  get '/feeds', to: "home_page#feeds"
  get '/managers/photo', to: "admin#photo"
  get '/managers/album', to: "admin#album"
  get '/managers/user', to: "admin#user"

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users do
    member do
      get :followings, :followers
    end
  end

  resources :albums do
    resources :likes, only: [:create, :destroy], module: :albums
    resources :images, :only => [:create, :destroy]
  end

  resources :photos do
    resources :likes, only: [:create, :destroy], module: :photos
  end

  resources :relationships,       only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  has_many :albums, dependent: :destroy
  has_many :likes, dependent: :destroy

  #for button follow in profile page
  has_many :active_relationships, class_name:  "Relationship",
                                foreign_key: "follower_id",
                                dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                 foreign_key: "followed_id",
                                 dependent:   :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :photos, through: :likes, source: :likeable, source_type: 'Photo'
  has_many :albums, through: :likes, source: :likeable, source_type: 'Album'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/assets/logoLogin.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def full_name
    [first_name, last_name].select(&:present?).join(' ').titleize
  end

  # Follows a user.
  def follow(other_user)
    followings << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    followings.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    followings.include?(other_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:edit, :update, :show, :destroy ]
  def index
    @users = User.all
  end

  def edit
  end


   def update
     if @user.update(user_params)
       redirect_to :admin
     else
       render 'edit'
     end
   end

  def show
    @get_photos = Photo.where(user_id: @user.id)
    @get_albums = Album.where(user_id: @user.id)
    @get_followings = @user.followings
    @get_followers = @user.followers
  end

  def destroy
    if @user.present?
      @user.destroy
    end
    redirect_to :admin
  end

  def followings
    @title = "Followings"
    @user  = User.find(params[:id])
    @users = @user.followings.paginate(page: params[:page])
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :activated)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "Follow", class: "btn mt-4 follow text-warning"%>
<% end %>

app/views/users/_follow_form.html.erb
<%unless current_user == user %>
  <div id="follow_form_<%= user.id %>">
    <% if current_user.following?(user) %>
      <%= render 'unfollow', user: user %>
    <% else %>
      <%= render 'follow', user: user %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-warning mt-4 following" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<%= render 'layouts/toolbar' %>

<section class="container-fluid bg-secondary p-0">
  <div class="row">
    <div class="col-md-2">
      <div class="container mt-3">
        <div class="navbar navbar-expand-md navbar-light bg-lignt p-0">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class=" collapse navbar-collapse p-0" id="collapsibleNavbar">
            <ul class="navbar-nav nav nav-tabs flex-column">
              <li class="nav-item p-0">
                <a class="nav-link text-primary" data-toggle="tab" href="#managePhotos"><b>Manage Photos</b></a>
              </li>
              <li class="nav-item p-0">
                <a class="nav-link text-primary" data-toggle="tab" href="#manageAlbums"><b>Manage Albums</b></a>
              </li>
              <li class="nav-item p-0">
                <a class="nav-link text-primary" data-toggle="tab" href="#ManageUsers"><b>Manage Users</b></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <article class=" col-md-8 bg-white" >
      <div class="d-flex justify-content-between">
        <h2 class="h2-title">Edit User Profile</h2>
        <div class="btn-back">
          <button class="btn btn-primary">Back</button>
        </div>

      </div>
        <hr>
        <%= form_for(@user) do |f| %>
          <div class="form-group row">
            <div class="col-md-3"></div>
            <div class="col-md-5 fix-position" >
              <div class="input-file-container">
                <img class=" avatar-show" src="/assets/img1.jpeg" id="image">
                <%= f.file_field :avatar, class:"input-file btn-change", id:"my-file", onchange:"showImage.call(this);" %>
                <label tabindex="0" for="my-file" class="input-file-trigger">CHANGE</label>
              </div>
            </div>
          </div>
          <div class="form-group row">
            <div class="col-md-3"></div>
            <div class="col-md-5">
              <h4 class="text-primary">Basic information</h4>
            </div>
          </div>
          <div class="form-group row">
            <label for="changeFirstName" class="col-md-3 col-form-label d-flex justify-content-end"><b>First name</b></label>
            <div class="col-md-5">
              <%= f.text_field :first_name, class:"form-control", id:"editFirstName", placeholder:"first name", required: true, autofocus: true %>
            </div>
          </div>
          <div class="form-group row">
            <label for="changeLastName" class="col-md-3 col-form-label d-flex justify-content-end"><b>Last name</b></label>
            <div class="col-md-5">
              <%= f.text_field :last_name, class:"form-control", id:"editLastName", placeholder:"last name", required: true, autofocus: true %>
            </div>
          </div>
          <div class="form-group row">
            <label for="changeEmail" class="col-md-3 col-form-label d-flex justify-content-end"><b>Email</b></label>
            <div class="col-md-5">
              <%= f.text_field :email, class:"form-control", id:"editEmail", placeholder:"email", required: true, autofocus: true %>
            </div>
          </div>
          <div class="form-group row">
            <label for="changePassword" class="col-md-3 col-form-label d-flex justify-content-end"><b>Password</b></label>
            <div class="col-md-5">
              <%= f.password_field :password,
                          placeholder:"Enter New password",
                          class:"form-control",
                          required: false,
                          input_html: { autocomplete: "new-password" } %>
            </div>
          </div>
          <div class="form-group row">
            <label for="active" class="col-md-3 col-form-label d-flex justify-content-end"><b>Active?</b></label>
            <div class="col-md-1">
              <%= f.check_box :activated, class: "form-control" %>
            </div>
          </div>
          <div class="form-group row">
            <div class="col-md-3"></div>
            <div class="col-md-5">
              <%= f.submit "Save", class:"btn btn-success" %>
            </div>
          </div>
        <% end %>
    </article>

  </div>
</section>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<% provide(:title, @user.full_name) %>
<%= render 'layouts/toolbar' %>
<section class="container-fluid">
  <!--Tab feeds va discover-->
  <div class="row">
    <%= render 'layouts/tab_feeds' %>
    <article class="tab-content col-md-8 p-0 mt-3  bg-white" >
      <!--tab profile-->
      <div class="container-fluid p-0">
        <div class="row m-5">
          <img src="<%= @user.avatar %>" class="rounded-circle mr-4 size-my-photos" id="avatarMain" >
          <div class="mt-4">
            <%unless current_user == @user %>
              <%= render 'follow_form', user: @user %>
            <% else %>
              <a href="/users/edit" type="button" class="btn btn-primary mt-4 btn-radius"><b>Edit Profile</b></a>
            <% end %>

            <h1 class="mt-3"><b><%= @user.full_name %></b></h1>
            <!-- Nav profile tabs -->
            <ul class="nav nav-tabs mt-3">
              <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#photosProfile"><b><%= @get_photos.count %></b><small> <b>PHOTOS</b></small></a>
              </li>
              <li class="nav-item d-inline-flex">
                <a class="nav-link" data-toggle="tab" href="#albumsProfile"><b><%= @get_albums.count %></b><small> <b>ALBUMS</b></small></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#followingsProfile" id="followings_tab_<%= @user.id %>"><b><%= @get_followings.count %></b><small> <b>FOLLOWINGS</b></small></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#followersProfile" id="followers_tab_<%= @user.id %>"><b><%= @get_followers.count %></b><small> <b>FOLLOWERS</b></small></a>
              </li>
            </ul>
          </div>
        </div>
      </div>

    <!--show content-->

      <div class="tab-content container-fluid">
        <div id="photosProfile" class=" tab-pane active">
          <%if current_user == @user %>
            <div class="row d-flex flex-row-reverse mr-3 mb-2">
              <a class="btn btn-success float-right btn-radius" href="<%= new_photo_path %>"><b>Add Photo</b></a>
            </div>
          <% end %>
          <div class="row">
            <% if @get_photos.any? %>
              <% @get_photos.each do |photo| %>
                <div class="col-12 col-sm-6 col-md-4 col-lg-3 text-center">
                  <div class="d-flex justify-content-center text-center size-image">
                    <%= image_tag photo.image , {class:"rounded-sm size-my-photos", style:"position: absolute; z-index: 0;"} if photo.image.attached?%>
                    <% if photo.sharing_mode? %>
                      <i class="fas fa-unlock fa-lg rounded-circle bg-secondary p-2 mt-1 btn-lock" ></i>
                      <% else %>
                      <i class="fas fa-lock fa-lg rounded-circle bg-secondary p-2 mt-1 btn-lock" ></i>
                    <% end %>
                    <%if current_user.id == @user.id %>
                      <%= link_to 'EDIT', edit_photo_path(photo), class:"btn btn-secondary btn-edit" %>
                    <% end %>
                  </div>
                  <div class="d-flex justify-content-center">
                    <p><%= photo.title %></p>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div><!--end tab show photo-->
        <div id="albumsProfile" class="tab-pane fade">
          <%if current_user == @user %>
            <div class="row d-flex flex-row-reverse mr-3 mb-2">
              <a class="btn btn-success float-right btn-radius" href="<%= new_album_path %>"><b>Add Albums</b></a>
            </div>
          <% end %>
          <div class="row">
            <% @get_albums.each do |album| %>
              <div class="col-12 col-sm-6 col-md-4 col-lg-3 text-center">
                <div class="d-flex justify-content-center m-0 text-center size-image">
                  <% album.images.each_with_index do |photo, index| %>
                    <% if (index != album.images.length - 1) && (index < 5) %>
                      <% a = (index*3+3).to_s %>
                      <%= image_tag photo.url, {class:"rounded-sm size-my-photos", style:"position: absolute; z-index: index; transform: rotate("+ a +"deg)"} %>
                    <% else %>
                      <%= image_tag photo.url, {class:"rounded-sm size-my-photos", style:"position: absolute; z-index: index;"} %>
                    <% end %>
                  <% end %>
                  <p class="rounded-circle bg-secondary p-3" style="position: absolute; z-index: <%= album.images.length %> + 1; margin-top: 70px; opacity: 0.7;"><b><%= album.images.length %><br><small>PHOTOS</small></b></p>
                  <% if album.sharing_mode? %>
                    <i class="fa fa-unlock fa-lg rounded-circle bg-secondary p-2 mt-1 btn-lock" style= "z-index: <%= album.images.length %> + 2;"></i>
                    <% else %>
                    <i class="fa fa-lock fa-lg rounded-circle bg-secondary p-2 mt-1 btn-lock" style= "z-index: <%= album.images.length %> + 2;"></i>
                  <% end %>
                  <%if current_user.id == @user.id %>
                    <a href="<%= edit_album_path(album) %>" class="btn btn-secondary btn-edit" style="z-index: <%= album.images.length %> + 3;">EDIT</a>

                  <% end %>
                </div>
                <div class="d-flex justify-content-center">
                  <p><%= album.title %></p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <!--end tab show album-->
        <div id="followingsProfile" class="tab-pane fade">
          <div class="row" id="moreFollowing_<%= @user.id %>">
            <% @get_followings.each do |user| %>
              <%= link_to user do %>
                <div class="col-12 col-sm-6 col-lg-3 p-1" id="following_<%= user.id %>_<%= @user.id %>">
                  <div class="card rounded-sm">
                    <div class="d-flex justify-content-center mt-3">
                      <img class="card-img-top rounded-circle avatar-profile" src="<%= user.avatar.url() %>" alt="Card image" >
                    </div>
                    <div class="card-body text-center" style="height: 230px;">
                      <h4 class="card-title"><b><%= user.full_name %> </b></h4>
                      <ul class="nav d-inline-flex">
                        <li class="m-2">
                          <a class="nav-link" data-toggle="tab" href="#"><b><%= user.photos.count %><br><small>PHOTOS</small></b></a>
                        </li>
                        <li class="m-2">
                          <a class="nav-link" data-toggle="tab" href="#"><b><%= user.albums.count %><br><small>ALBUMS</small></b></a>
                        </li>
                      </ul>
                      <%unless current_user.id == user.id %>
                        <div id="following_form_<%= user.id %>">
                          <% if current_user.following?(user) %>
                            <%= render 'unfollow', user: user %>
                          <% else %>
                            <%= render 'follow', user: user %>
                          <% end %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <!--end tab show followings-->
        <div id="followersProfile" class="tab-pane fade">
          <div class="row" id="moreFollowers_<%= @user.id %>">
            <% @get_followers.each do |user| %>
              <%= link_to user do %>
                <div class="col-12 col-sm-6 col-lg-3 p-1 %>" id="follower_<%= user.id %>_<%= @user.id %>">
                  <div class="card rounded-sm">
                    <div class="d-flex justify-content-center mt-3">
                      <img class="card-img-top rounded-circle avatar-profile" src="<%= user.avatar.url() %>" alt="Card image">
                    </div>
                    <div class="card-body text-center" style="height: 230px;">
                      <h4 class="card-title"><b><%= user.full_name %></b></h4>
                      <ul class="nav d-inline-flex">
                        <li class="m-2">
                          <a class="nav-link" data-toggle="tab" href="user_path(user)"><b><%= user.photos.count %><br><small>PHOTOS</small></b></a>
                        </li>
                        <li class="m-2">
                          <a class="nav-link" data-toggle="tab" href="user_path(user)"><b><%= user.albums.count %><br><small>ALBUMS</small></b></a>
                        </li>
                      </ul>
                      <%unless current_user.id == user.id %>
                        <div id="follower_form_<%= user.id %>">
                          <% if current_user.following?(user) %>
                            <%= render 'unfollow', user: user %>
                          <% else %>
                            <%= render 'follow', user: user %>
                          <% end %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <!--end tab show followers-->
      </div>
      <!--end class tab-content-->
    </article>
  </div>
</section>