config/routes.rb
Rails.application.routes.draw do
  root to: "home_page#discovers"

  get '/feeds', to: "home_page#feeds"
  get '/managers/photo', to: "admin#photo"
  get '/managers/album', to: "admin#album"
  get '/managers/user', to: "admin#user"

  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users do
    member do
      get :followings, :followers
    end
  end

  resources :albums do
    resources :likes, only: [:create, :destroy], module: :albums
    resources :images, :only => [:create, :destroy]
  end

  resources :photos do
    resources :likes, only: [:create, :destroy], module: :photos
  end

  resources :relationships,       only: [:create, :destroy]
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy
  # has_many :image_albums
  # accepts_nested_attributes_for :image_albums, allow_destroy: true
  mount_uploaders :images, ImagesUploader

  scope :published_album, -> {
    where(sharing_mode: true)
  }

end

app/controllers/albums/likes_controller.rb
class Albums::LikesController < LikesController
  before_action :authenticate_user!
  before_action :set_album

  def create
    @album = Album.find(params[:album_id])
    @like = @album.likes.new
    @like.user = current_user
    @like.save
    respond_to do |format|
      format.html { redirect_to @like }
      format.js { render :file => "likes/create_album.js.erb" }
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @like.destroy
    respond_to do |format|
      format.html { redirect_to @like }
      format.js { render :file => "/likes/destroy_album.js.erb" }
    end
  end

  private
  def set_album
    @album = Album.find(params[:album_id]) if params[:id]
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_album, except: [:index, :new, :create, :delete_image_attachment]
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @album = Album.new
    @album.user = current_user
  end

  def edit
  end

  def create
    @album = Album.new(album_params)
    @album.images = params[:images]
    @album.user = current_user

    respond_to do |format|
      if @album.save
        format.html { redirect_to current_user, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: current_user }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to current_user, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: current_user }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_album
      @album = Album.find(params[:id])
    end

    def album_params
      params.require(:album).permit(:title, :description, :sharing_mode, {images: []})
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album_modal.html.erb
<!-- Modal Header -->
<div class="modal-header">
  <h4><b><%= album.title %></b></h4>
  <button type="button" class="close" data-dismiss="modal">×</button>
</div>

<!-- Modal body -->
<div class="modal-body">
  <div id="show_album" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ul class="carousel-indicators">
      <% album.images.each_with_index do |photo, index| %>
        <% if index != 0 %>
          <li data-target="#show_album" data-slide-to=index></li>
        <% else %>
          <li data-target="#show_album" data-slide-to="0" class="active"></li>
        <% end %>
      <% end %>
    </ul>
    <!-- The slideshow -->
    <div class="carousel-inner">
      <% album.images.each_with_index do |photo, index| %>
        <% if index != 0 %>
          <div class="carousel-item">
            <img class="size-modal w-100" src="<%= photo.url %>" alt="Load image false">
          </div>
        <% else %>
          <div class="carousel-item active">
            <img class="size-modal w-100" src="<%= photo.url %>" alt="Load image false">
          </div>
        <% end %>
      <% end %>
    </div>
    <!-- Left and right controls -->
    <a class="carousel-control-prev" href="#show_album" data-slide="prev">
      <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#show_album" data-slide="next">
      <span class="carousel-control-next-icon"></span>
    </a>
  </div>
</div>
<!-- Modal footer -->
<div class="modal-header">
  <p><%= album.description %></p>
</div>

app/views/albums/_form.html.erb
<%= render 'layouts/toolbar' %>
<section class="container-fluid">
  <!--Tab feeds va discover-->
  <div class="row">
    <%= render '/layouts/tab_feeds' %>
    <article class="tab-content col-md-9 p-0 mt-5" >
      <div class="col-sm-8 col-lg-10 bg-white">
        <div class="container-fluid">
          <div class="row">
            <div class="col-12">
              <h3 class="pt-4"><b>New Album</b></h3>
              <hr>
            </div>
          </div>
          <%= simple_form_for album,html: { multipart: true}, remote: true do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
            <div class="form-inputs">
              <div class="row">
                <div class="col-12 col-lg-6">
                  <div class="form-group">
                    <label>Title</label>
                    <%= f.text_field :title, class:"form-control", placeholder:"Enter photo title" %>
                  </div>
                  <div class="form-group">
                    <label>Sharing Mode</label>
                    <%= f.select(:sharing_mode, options_for_select([['Public', true], ['Private', false]]), {}, {class: "form-control w-50"}) %>
                  </div>
                </div>
                <div class=" col-12 col-lg-6">
                  <div class="form-group">
                    <label>Desription</label>
                    <%= f.text_area :description, class:"form-control",rows:"6", placeholder:"Enter description" %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col images">
                  <% if album.image_albums.any? %>
                    <% album.image_albums.each do |img| %>
                        <div id="image_<%= img.id %>">
                          <div class="float-left m-2">
                            <div ng-repeat="file in imagefinaldata" class="img-wrp">
                              <%= image_tag img.image_url, {class:"size-my-photos"} %>
                              <%= link_to delete_image_attachment_album_url(img.id), method: :delete do %>
                                <img class="btn-close-album m-1" src="/assets/close.png" />
                              <% end %>
                            </div>
                          </div>
                        </div>
                    <% end %>
                  <% end %>
                  <div class="upload-btn-wrapper float-left size-my-photos m-2">
                    <%= f.fields_for :image_albums do |p| %>
                      <div class="field size-my-photos">
                        <button class="btn-upload"><img src="/assets/plus4.png"></button>
                        <%= p.file_field :image, multiple: true, name: "image_albums[image][]", class: "upload-image btn-upload" %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="form-actions row mt-5 m-1">
              <%= f.submit "Save", class:"btn btn-submit mr-2" %>
              <%= link_to album, method: :delete,
                                 data: { confirm: 'Are you sure?' } do %>
                <button class=" btn btn-delete ml-2"> <i class="far fa-trash-alt"></i> Delete</button>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </article>
  </div>
</section>

app/views/albums/edit.html.erb
<% provide(:title, "Edit album") %>
<%= render 'layouts/toolbar' %>
<section class="container-fluid">
  <!--Tab feeds va discover-->
  <div class="row">
    <%= render '/layouts/tab_feeds' %>
    <article class="tab-content col-md-9 mt-2" >
      <div class="col-sm-8 col-lg-10 bg-white">
        <div class="container-fluid">
          <div class="row">
            <div class="col-12">
              <h3 class="pt-4"><b>Edit Album</b></h3>
              <hr>
            </div>
          </div>
          <%= simple_form_for @album,url: album_images_path(@album), method: :post, :html => {:multipart => true, id: "edit_album"}, remote: true do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
            <div class="form-inputs">
              <div class="row">
                <div class="col-12 col-lg-6">
                  <div class="form-group">
                    <label>Title</label>
                    <%= f.text_field :title, class:"form-control", placeholder:"Enter photo title" %>
                  </div>
                  <div class="form-group">
                    <label>Sharing Mode</label>
                    <%= f.select(:sharing_mode, options_for_select([['Public', true], ['Private', false]]), {}, {class: "form-control w-50"}) %>
                  </div>
                </div>
                <div class=" col-12 col-lg-6">
                  <div class="form-group">
                    <label>Desription</label>
                    <%= f.text_area :description, class:"form-control",rows:"6", placeholder:"Enter description" %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col images">
                  <% @album.images.each_with_index do |img, index| %>
                    <div id="image_<%= img %>">
                      <div class="float-left m-2">
                        <div ng-repeat="file in imagefinaldata" class="img-wrp">
                          <%= image_tag img.url, {class:"size-my-photos"} %>
                          <%= link_to album_image_path(@album, index), :method => :delete, data: { confirm: "Are you sure you want to delete this image?" } do %>
                            <img class="btn-close-album m-1" src="/assets/close.png" />
                          <% end %>
                        </div>
                      </div>
                    </div>
                  <% end %>
                  <div class="upload-btn-wrapper float-left size-my-photos m-2">
                    <div class="field size-my-photos">
                      <button class="btn-upload"><img src="/assets/plus4.png"></button>
                      <%= f.file_field :images, multiple: true, class: "btn-upload" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="form-actions row mt-5 m-1">
              <%= f.submit "Save", class:"btn btn-submit mr-2" %>
              <%= link_to @album, method: :delete,
                                 data: { confirm: 'Are you sure?' } do %>
                <button class=" btn btn-delete ml-2"> <i class="far fa-trash-alt"></i> Delete</button>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </article>
  </div>
</section>

app/views/albums/new.html.erb
<% provide(:title, "New album") %>
<%= render 'layouts/toolbar' %>
<section class="container-fluid">
  <!--Tab feeds va discover-->
  <div class="row">
    <%= render '/layouts/tab_feeds' %>
    <article class="tab-content col-md-9 mt-2" >
      <div class="col-sm-8 col-lg-10 bg-white">
        <div class="container-fluid">
          <div class="row">
            <div class="col-12">
              <h3 class="pt-4"><b>New Album</b></h3>
              <hr>
            </div>
          </div>
          <%= simple_form_for @album, html: { multipart: true }, remote: true do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
            <div class="form-inputs">
              <div class="row">
                <div class="col-12 col-lg-6">
                  <div class="form-group">
                    <label>Title</label>
                    <%= f.text_field :title, class:"form-control", placeholder:"Enter photo title" %>
                  </div>
                  <div class="form-group">
                    <label>Sharing Mode</label>
                    <%= f.select(:sharing_mode, options_for_select([['Public', true], ['Private', false]]), {}, {class: "form-control w-50"}) %>
                  </div>
                </div>
                <div class=" col-12 col-lg-6">
                  <div class="form-group">
                    <label>Desription</label>
                    <%= f.text_area :description, class:"form-control",rows:"6", placeholder:"Enter description" %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col images ">
                  <%= image_tag(@album.images_url) if @album.images? %>
                    <div class="upload-btn-wrapper float-left size-my-photos m-2">
                      <div class="field size-my-photos">
                        <button class="btn-upload"><img src="/assets/plus4.png"></button>
                        <%= f.file_field :images, multiple: true, class: "btn-upload" %>
                      </div>
                    </div>
                </div>
              </div>
            </div>
            <div class="form-actions row mt-5 m-1">
              <%= f.submit "Save", class:"btn btn-submit mr-2" %>
            </div>
          <% end %>
        </div>
      </div>
    </article>
  </div>
</section>

app/views/albums/show.js.erb
$("#modal_album").find(".modal-content").html("<%= j (render 'album_modal', album: @album) %>");
$("#modal_album").modal();